# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Repositories/FPGA/Xilinx/Vivado/SevenSegmentsTest/SevenSegmentsTest.srcs/sources_1/bd/Main/ip/Main_axi_gpio_0_0/Main_axi_gpio_0_0.xci
# IP: The module: 'Main_axi_gpio_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Repositories/FPGA/Xilinx/Vivado/SevenSegmentsTest/SevenSegmentsTest.srcs/sources_1/bd/Main/ip/Main_axi_gpio_0_0/Main_axi_gpio_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Main_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/Repositories/FPGA/Xilinx/Vivado/SevenSegmentsTest/SevenSegmentsTest.srcs/sources_1/bd/Main/ip/Main_axi_gpio_0_0/Main_axi_gpio_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Main_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/Repositories/FPGA/Xilinx/Vivado/SevenSegmentsTest/SevenSegmentsTest.srcs/sources_1/bd/Main/ip/Main_axi_gpio_0_0/Main_axi_gpio_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Main_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/Repositories/FPGA/Xilinx/Vivado/SevenSegmentsTest/SevenSegmentsTest.srcs/sources_1/bd/Main/ip/Main_axi_gpio_0_0/Main_axi_gpio_0_0.xci
# IP: The module: 'Main_axi_gpio_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Repositories/FPGA/Xilinx/Vivado/SevenSegmentsTest/SevenSegmentsTest.srcs/sources_1/bd/Main/ip/Main_axi_gpio_0_0/Main_axi_gpio_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Main_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/Repositories/FPGA/Xilinx/Vivado/SevenSegmentsTest/SevenSegmentsTest.srcs/sources_1/bd/Main/ip/Main_axi_gpio_0_0/Main_axi_gpio_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Main_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/Repositories/FPGA/Xilinx/Vivado/SevenSegmentsTest/SevenSegmentsTest.srcs/sources_1/bd/Main/ip/Main_axi_gpio_0_0/Main_axi_gpio_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Main_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
