



set_property IOSTANDARD LVTTL [get_ports {muxer_tri_io[0]}]
set_property IOSTANDARD LVTTL [get_ports {muxer_tri_io[1]}]
set_property IOSTANDARD LVTTL [get_ports {muxer_tri_io[2]}]
set_property IOSTANDARD LVTTL [get_ports {muxer_tri_io[3]}]
set_property IOSTANDARD LVTTL [get_ports {muxer_tri_io[4]}]
set_property IOSTANDARD LVTTL [get_ports {segments_tri_o[0]}]
set_property IOSTANDARD LVTTL [get_ports {segments_tri_o[1]}]
set_property IOSTANDARD LVTTL [get_ports {segments_tri_o[2]}]
set_property IOSTANDARD LVTTL [get_ports {segments_tri_o[3]}]
set_property IOSTANDARD LVTTL [get_ports {segments_tri_o[4]}]
set_property IOSTANDARD LVTTL [get_ports {segments_tri_o[5]}]
set_property IOSTANDARD LVTTL [get_ports {segments_tri_o[6]}]
set_property IOSTANDARD LVTTL [get_ports {segments_tri_o[7]}]
set_property DRIVE 24 [get_ports {muxer_tri_io[0]}]
set_property DRIVE 24 [get_ports {muxer_tri_io[1]}]
set_property DRIVE 24 [get_ports {muxer_tri_io[2]}]
set_property DRIVE 24 [get_ports {muxer_tri_io[3]}]
set_property DRIVE 24 [get_ports {muxer_tri_io[4]}]
set_property DRIVE 24 [get_ports {segments_tri_o[0]}]
set_property DRIVE 24 [get_ports {segments_tri_o[1]}]
set_property DRIVE 24 [get_ports {segments_tri_o[2]}]
set_property DRIVE 24 [get_ports {segments_tri_o[3]}]
set_property DRIVE 24 [get_ports {segments_tri_o[4]}]
set_property DRIVE 24 [get_ports {segments_tri_o[5]}]
set_property DRIVE 24 [get_ports {segments_tri_o[6]}]
set_property DRIVE 24 [get_ports {segments_tri_o[7]}]
set_property PACKAGE_PIN E18 [get_ports {segments_tri_o[0]}]
set_property PACKAGE_PIN E19 [get_ports {segments_tri_o[2]}]
set_property PACKAGE_PIN D20 [get_ports {segments_tri_o[1]}]
set_property PACKAGE_PIN D19 [get_ports {segments_tri_o[3]}]
set_property PACKAGE_PIN F16 [get_ports {segments_tri_o[4]}]
set_property PACKAGE_PIN B20 [get_ports {segments_tri_o[5]}]
set_property PACKAGE_PIN F17 [get_ports {segments_tri_o[6]}]
set_property PACKAGE_PIN C20 [get_ports {segments_tri_o[7]}]
set_property PACKAGE_PIN L14 [get_ports {muxer_tri_io[0]}]
set_property PACKAGE_PIN J16 [get_ports {muxer_tri_io[1]}]
set_property PACKAGE_PIN L15 [get_ports {muxer_tri_io[2]}]
set_property PACKAGE_PIN K16 [get_ports {muxer_tri_io[3]}]
set_property PACKAGE_PIN M14 [get_ports {muxer_tri_io[4]}]
set_property PULLUP true [get_ports {segments_tri_o[0]}]
