# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/Main_wrapper.xdc

# Block Designs: bd/Main/Main.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Main || ORIG_REF_NAME==Main} -quiet] -quiet

# IP: bd/Main/ip/Main_processing_system7_0_0/Main_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Main_processing_system7_0_0 || ORIG_REF_NAME==Main_processing_system7_0_0} -quiet] -quiet

# IP: bd/Main/ip/Main_axi_gpio_0_0/Main_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Main_axi_gpio_0_0 || ORIG_REF_NAME==Main_axi_gpio_0_0} -quiet] -quiet

# IP: bd/Main/ip/Main_ps7_0_axi_periph_0/Main_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Main_ps7_0_axi_periph_0 || ORIG_REF_NAME==Main_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/Main/ip/Main_rst_ps7_0_50M_0/Main_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Main_rst_ps7_0_50M_0 || ORIG_REF_NAME==Main_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/Main/ip/Main_axi_gpio_1_0/Main_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Main_axi_gpio_1_0 || ORIG_REF_NAME==Main_axi_gpio_1_0} -quiet] -quiet

# IP: bd/Main/ip/Main_xbar_0/Main_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Main_xbar_0 || ORIG_REF_NAME==Main_xbar_0} -quiet] -quiet

# IP: bd/Main/ip/Main_auto_pc_0/Main_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Main_auto_pc_0 || ORIG_REF_NAME==Main_auto_pc_0} -quiet] -quiet

# XDC: bd/Main/Main_ooc.xdc
